### ISSUE TITLE
Does it need to import anything to use this library?

### ISSUE THREAD

**Issue by elgs** [Thomvis/BrightFutures#103]
Normally I need to import something before I can use this library. For this one, I don't see it's mentioned anywhere in the `README.md`. So do I need to import anything before I can use it? Thanks.

**Comment by Thomvis** [comment]
Hi, thanks for showing an interest in using BrightFutures.

The easiest way to get up and running is by using Carthage or CocoaPods. You can also manually compile the library and add it as a dependency.

Hope this helps!
