### ISSUE TITLE
generic error handling

### ISSUE THREAD

**Issue by dileping** [Thomvis/BrightFutures#107]
Hi guys,

first of all I really like BrightFutures, they are awesome!

I have a question about error handling, though. I'm not sure how to handle the errors if I have no idea what error is going to happen while the code is running.

Could you point me to a solution?

Thanks in advance!

**Comment by Thomvis** [comment]
Hi and thanks for the kind words. Sorry you're having problems.

It'd really help if you could provide a short code sample that demonstrates the issue you're encountering.

Thanks!

**Comment by dileping** [comment]
Hi!

I have created a pull request with the functionality I'm missing: https://github.com/Thomvis/BrightFutures/pull/108

The main idea is to allow the future to fail from exception and still be recoverable from a generic error (ErrorType).

I've started using the library extensively for a big project (framework). Will open source one soon as well. So I hope I could help making BrightFutures better with intensive testing and I'm pretty much sure this is not my last PR :)

Thanks,
Daniel

**Comment by matthew-healy** [comment]
I'm possibly being an idiot, but I don't understand what adding `AnyError` gives to consumers. ErrorType already covers every single error that can be thrown, and if you *did* want a wrapper, there's already `BrightFuturesError.External(ErrorType)` which is, as far as I can see, equivalent to your `AnyError` struct.

Agree with @Thomvis that I'd like to see the problem this solves, rather than your proposed solution.

**Comment by dileping** [comment]
Unfortunately BrightFuturesError.External does not solve anything, because it's a template and you have to set a concrete class there.

You can find usage example in the tests I have added along with the functionality. Here is one:
```swift
func something() throws -> String {
  return "myresult"
}

future {
  return try something()
}.recover { e in
  switch e {
    //handle your cases here
    default: return "recovered"
  }
}
```

Before you had to catch it inside the future, wrap with a certain error type and then you are good to go. This is just more handy for real life scenarios assuming errors being thrown are first class citizens in Swift 2.0.

**Comment by matthew-healy** [comment]
Yep, okay, I get why it's necessary.

**Comment by Thomvis** [comment]
Thanks for the elaborate explanation and the PR! 

I will have more time to look at it after the holidays, but my first thought is if this could perhaps already  be achieved using Result's `materialize` and/or initialiser that takes a throwing (auto)closure. 

The PR adds a significant amount of code, so I'll definitely need to spend more time looking at the issue and possible alternative solutions before merging it in.

Thanks again!

**Comment by dileping** [comment]
Thanks for looking into the PR. Let me know if you need anything from my side to help merging it or if any questions will arise. I will be glad to help.

**Comment by Thomvis** [comment]
@dileping It would be great if you could have a look at Result's capabilities to wrap throwing closures and explain why that would not/also work!

**Comment by dileping** [comment]
@Thomvis I had a brief look, and it seems to be not capable to handle raw ErrorType (which is very important for me). Moreover what I have implemented there adds some "sugar" and is very easy to use.

I will take a deeper look into Result, meanwhile I will appreciate a lot if you could take a look through my code as well.

**Comment by dileping** [comment]
@Thomvis I had a look at Result and it's capabilities and it's good for certain goals, but here are several reasons why I have implemented it in another way:

* Result materialize uses NSError as an exact type. I want to have a capability to use a raw ErrorType

* it adds certain level of complexity and you will have to use it like

```swift
future {
  return materialize {
    //throwing code here
  }
}
```

* The code I have provided just enables you to use throwing techniques from inside the futures out of the box (even in map functions and so on)

I hope all this makes sense. If it makes sense for me (I'm already using it intensively) I hope it would be helpful for others as well.

Looking forward to have some feedback of yours.

Thanks,
Daniel

**Comment by Thomvis** [comment]
I understand and agree that it makes sense to have a type-erased error type. I am however not sure that it should be part of BrightFutures itself. The second part of your PR, which introduces the throwing versions of map, recover, etc. adds a lot of code to the library. That warrants further deliberation. Therefore, I'd like to continue to explore how you could add this on top of BrightFutures in an good way.

For the cases where you want to execute throwing code inside a map, recover, etc., I think a wrapping function (like Result's `materialize`) isn't too bad. You could make your own that works with your AnyError type. Am I correct in thinking that there are a lot of cases as well where your map, recover, etc. will not throw? In that case you keep the concise syntax and type safety that we already have.

I think it is an advantage of BrightFutures/Result over the built in Swift errors that you have typesafety and I like to keep that type information available as long as possible. Of course, sometimes you want to bring together different error types and treat them the same. For those cases, a wrapping error type (like AnyError) combined with `mapError` is my preferred solution.

I'll admit that I'm not super convinced of Swift's error throwing/catching mechanism and therefore used `Result` in a lot of my code instead. But that's just me and if there are more people that run into these issues when using BrightFutures and Swift's errors, we should consider it for the next major release.

**Comment by dileping** [comment]
@Thomvis Thanks for taking a closer look at my PR. I understand your concerns about keeping the library as small as possible, which obviously makes sense. The reason why I have added this functionality, though, is because I already desperately need it for my project (pretty big open source framework, will tell more once it's online, which is gonna be this month) and Futures is one of the cornerstones of it. I will need one more feature very soon: custom threading model, however I can live without it for now.

Meanwhile I could keep a separate fork, but I will be very glad to cooperate on the Futures together. May be the use cases will be more clear to you once you see how it works in my framework.

**Comment by Thomvis** [comment]
Thanks for understanding. If you want to talk about the threading model, please open a new issue.

Once your framework is in the open, I'd be happy to have a look at it and see how we can remove the need for a fork.

Good luck!

**Comment by Thomvis** [comment]
@dileping thanks for the update in https://github.com/Thomvis/BrightFutures/issues/91 and congrats on the launch! 

I checked out the project and looked through the code but couldn't easily find the places where you ran into limitations with BF. Can you perhaps point me to a few occurrences? 

I did see https://github.com/crossroadlabs/Express/blob/1b66e1a882dddd0038fe74ea06ec75397a2e1e16/Express/Action.swift#L95:

```
future(ImmediateExecutionContext) {
    throw ExpressError.PageNotFound(path: request.path)
}
```

and think you can write it more clearly like this: 

`Future(error: ExpressError.PageNotFound(path: request.path))`

That should be more efficient (and it supported by default). But this is obviously not the main issue you had with BF.

**Comment by dileping** [comment]
Hi @Thomvis, thanks for taking a look at [Swift Express](https://github.com/crossroadlabs/Express), I really appreciate this a lot!

Let me tell you a couple of reasons on why exactly we need this `throw` and generic error thingy:
1. The framework is based on the futures a lot. Very much like Play framework does. I want to let our users to throw any error at any time from inside the future code.
2. Assuming we are getting from the user the Future (or the code that generates the Future) we have to keep them somehow internally. We never know what error might happen in the user's code, and I don't want to limit the user with a few options or even wrapping. So this is mainly where from the generic error handling comes. I'm completely OK to maintain this functionality further inside BrightFutures to make the decision easier for you.

The bottom line: if I were using BrightFutures for the app and just write my code - I most probably would be very happy with error handling capabilities currently available. Still, when it comes to generalisation, and making users of Swift Express happy - we really need it.

Another thing we might really need soon is to tweak the threading model somehow. What you currently have is great and is suitable for most cases, but what we need to do it is to change the default behaviour to make it more of a "server style". I know we can tell out users to user our custom queues, but it will make the user code more cumbersome and less attractive to the final user. So I will appreciate a lot if you could reopen that issue as well for further discussion.

One of the main ideas of Swift Express is to make users capable of writing very simple code still having the caps of "power tools". Basically both requirements above are coming from this vision.
