### ISSUE TITLE
Provide a way to "sequence" a dictionary containing futures

### ISSUE THREAD

**Issue by phatmann** [Thomvis/BrightFutures#110]
The `sequence` method converts a SequenceType of futures into a future containing an array. I would like a similar function for Dictionary. For example, I have a dictionary `[String: Future<Double>]` that  I want to convert to `Future<[String: Double]>`. Then I can wait on the all the futures to complete.

This can currently be done by extracting the values into an array, using the `sequence` method, and then recreating a dictionary using the sequenced values. But this is not very elegant.

**Comment by Thomvis** [comment]
I think it makes sense to have this indeed, and it could leverage the `sequence` implementation on `SequenceType`s. Would you be interested in making a PR with the implementation & tests?

**Comment by phimage** [comment]
I try to achieve this functionality on `Dictionary` but with the "not very elegant" that describe @phatmann (in fact I create a dictionary using the sequence/traverse values)

https://github.com/phimage/BrightFutures/blob/feature-dictionaryfuture/BrightFutures/Dictionary%2BBrightFutures.swift

maybe the method name is not appropriate

**Comment by phimage** [comment]
if you talk about my code in my fork
try to download my project and let Xcode convert it to swift 4.1
