### ISSUE TITLE
sequence().onSuccess called immediately

### ISSUE THREAD

**Issue by LucidityDesign** [Thomvis/BrightFutures#111]
When I run the following code, `onComplete` and `onSuccess` is called before the geoCoder completionHandler is finished. Can you help me please to get this running?

```
self.uploadContentSequence = [Future<Future<Void, NoError>, NoError>]();
        
for post in posts {
     self.uploadContentSequence.append(future(self.preparePostUpload(post)))
}

self.uploadContentSequence.sequence().onComplete { (_) -> Void in
    print("onComplete")
}.onSuccess { (_) -> Void in
    print("onSuccess")
}.onFailure { (_) -> Void in
    print("onFailure")
}

[...]

func preparePostUpload(post: Post) -> Future<Void, NoError> {
    let promise = Promise<Void, NoError>()
    
    [...]
    
    let postLocation = CLLocation(latitude: Double(post.lat!), longitude: Double(post.lng!))
    let geocoder = CLGeocoder();
    let countryCode = NSLocale.currentLocale().objectForKey(NSLocaleCountryCode) as! String
    post.country = countryCode
    geocoder.reverseGeocodeLocation(postLocation, completionHandler: { (placemarks, locError) -> Void in
        [...]
        promise.success()
    });
    
    return promise.future
}
```

**Comment by phimage** [comment]
Why did you make a future of future `Future<Future` using `future(self`?
Just remove it

(I think this useless Future succeed just by executing the code "create an other future", there is no wait)

**Comment by Thomvis** [comment]
Thanks @phimage for the suggestion. The issue indeed is with the additional wrappign of the futures from `preparePostUpload` with `future()`. By doing this you're creating a completed future that has an uncompleted future inside of it. If you remove that layer of indirection and define `uploadContentSequence` as  `[Future<Void, NoError>]()` you should have better results.

**Comment by LucidityDesign** [comment]
Oh yes, you were right. Thank you both very much!
