### ISSUE TITLE
BrightFutures needs a 1.0 release

### ISSUE THREAD

**Issue by Thomvis** [Thomvis/BrightFutures#12]
This issue is created to track the progress towards releasing a 1.0 version. Please chime in if you have any feedback or requests!

TODO:
- [x] Reconsider the default callback thread. Callbacks are currently scheduled on a background thread (dispatch global queue) unless an execution context is explicitly given. Maybe it is better to make the main thread the default callback thread. This makes a lot of sense in UIKit apps.
- [x] I don't like that most methods are defined twice: once with an execution context and once without an execution context. I'd think that it is possible to use optional parameters.
- [x] The naming of `Future.succeeded(..)` and `f.succeeded()` (same goes for `failed`) is confusing.
- [x] I'm not sure if the switch-case shorthand provided through `f.completed({}, {})`(and in a lesser way in `f.succeeded { }` and `f.failed { }` adds enough value to justify its existence.
- [x] Both `Future` and `TaskResult` have `succeeded`, `failed` and `completed` (/`handle`) methods, which seems duplicate.
- [x] I don't like the use of `TaskResultValueWrapper`. Luckily, it is almost never exposed through public API.
- [x] Not all `FutureUtils` functions from Scala have been ported over yet
- [x] Decide whether `Future` should be a pure functional future (two states: pending or complete), more like a 'task' (pending, complete, cancelled, succeeded, failed) or somewhere in between
- [x] Wrap up 1.0 documentation

Postponed until after 1.0:
- ~~The methods in `FutureUtils` should work on any `SequenceType`, not only on `Array`~~
- ~~Move helper classes (Queue, Semaphore, ExecutionContext) to a separate framework~~
- ~~A logo?~~
- ~~Add Objective-C support~~

**Comment by Thomvis** [comment]
Added "Decide whether Future should be a pure functional future (two states: pending or complete), more like a 'task' (pending, complete, cancelled, succeeded, failed) or somewhere in between" to the list of items

**Comment by wvteijlingen** [comment]
Regarding that, it would be nice if we could subclass Future/Task and add more types of 'results'. Then we could use it like this, for example when communicating with an API:

```swift
someFuture.onSuccess {
  // Success
}.onAPIFailure { error in
  // Error returned from the server. E.g. 'internal server error'.
}.onFailure { error
  // Error returned from the framework. E.g. 'no network connection'.
}
```

**Comment by Thomvis** [comment]
I agree that would be nice. We could enable this by subclassing Future (e.g. APIFuture) and add additional callbacks, which could be tiny wrappers around the 'native' callbacks.

**Comment by wvteijlingen** [comment]
The problem I see is that throughout the BrightFutures framework, `Future<T>` types are returned. Subclassing does't really work because for example `onSuccess` returns the base `Future<T>` type.

Too bad extensions of generics in other modules are not supported yet; that would be a great solution.

**Comment by Thomvis** [comment]
We might be able to solve this by creating a FutureType protocol and return Self from those methods. Interesting.

**Comment by Thomvis** [comment]
@wvteijlingen If you still would like the functionality that you described in your earlier comments, please file a separate issue to make sure it doesn't get lost.

**Comment by Thomvis** [comment]
I just marked the sub-task "Decide whether Future should be a pure functional future (two states: pending or complete), more like a 'task' (pending, complete, cancelled, succeeded, failed) or somewhere in between" as completed. I think the `Future` type as it is now is a good balance of a pure functional future and a practical one.

Pausing, cancellation & progress will not be part of the core BrightFutures `Future`, but I've started working on a wrapper around `NSProgress` ([Thomvis/GoodProgress](https://github.com/Thomvis/GoodProgress)) that offers such functionality and envision a third library that combines GoodProgress and BrightFutures.

**Comment by tmu** [comment]
I think you (we) should keep BrightFutures 1.0 / master compatible with Swift 1.1, because apps compiled with XCode 6.3 Beta / Swift 1.2 can't be submitted to AppStore. Only official XCode builds + XCode GM can be used for App Store submissions and those are likely available around April-June.

If you want to forget Swift 1.1 already and keep BrightFutures 1.0 compatible only with Swift 1.2 , I can take a responsibility of Swift 1.1 fork and backport some important production code features like InvalidationTokens to it.

**Comment by Thomvis** [comment]
Thanks to @tmu, master is compatible with Swift 1.1 again. There's a `swift1.2` branch that works well for Swift 1.2. When Swift 1.2 is released to the public, master will switch to Swift 1.2 and, if needed, a Swift 1.1 compatible fork will be created.

**Comment by bejar37** [comment]
Sorry for just dropping in on this, looks like a great library! Was there a resolution on the "adaptive callback" queue issue? I definitely think it'll make BrightFutures a lot nicer for us app developers.

**Comment by Thomvis** [comment]
@bejar37 Yes, the adaptive callback queue has been implemented for a while now. You can read about it in the readme: https://github.com/Thomvis/BrightFutures#default-threading-model.

**Comment by bejar37** [comment]
@Thomvis, ah, I missed that in the docs. I was referring to this:
```swift
future {
//This is not the main thread, don't do anything that requires being on the main thread
}
```
I'm not sure how surprised people would be by this behavior, but I think that in iOS this is somewhat of a liability.

I understand that it makes the interface less clean, but the right thing to do here might be to require an explicit execution context (perhaps by passing in an enum member?) when a future is explicitly created like this.

**Comment by Thomvis** [comment]
@bejar37 I would say that is quite clear from the docs that the closure handed to `future` is executed asynchronously. I also think it does not make much sense to execute a future's closure on the main thread.

I haven't heard yet from people that are having issues with this, so I'd vote for keeping the `future` function as-is, i.e. with an optional execution context.

**Comment by tonyarnold** [comment]
@Thomvis how can I help with ObjC support? What's been done to date?

**Comment by Thomvis** [comment]
@tonyarnold ObjC support is pretty far already (see https://github.com/Thomvis/BrightFutures/pull/27). I think it is still missing some tests, a FutureUtils equivalent, the invalidation tokens and that's it. If you want to have a look at any of those missing pieces, that would be helpful. Let's discuss this in the PR. Thanks!

**Comment by Thomvis** [comment]
I've updated the list to reflect the items that I'd like to postpone until after 1.0. Objective-C support is nearly done so I'm hoping 1.0 can be released pretty soon.

**Comment by wvteijlingen** [comment]
Is there a list of things that still need to be done for Objective-C support?

**Comment by Thomvis** [comment]
I'm thinking about stopping Objective-C support development (at least for 1.0). I have to admit that the reason is a bit selfish: I have been working in Swift more and more lately. 

Let me know if anybody was looking forward to this. Otherwise I'll go ahead and clear that of the list of things blocking a 1.0.0 release.

**Comment by tonyarnold** [comment]
I don't think that's selfish — just a reality of running a project with a single developer contributing. I was keen on Objective-C support, but it can definitely wait until there's more time. It shouldn't hold up 1.0.

**Comment by zenkimoto** [comment]
I agree.  I don't think Objective-C support should hold BrightFutures from reaching 1.0.0 release.

**Comment by Thomvis** [comment]
🎉 BrightFutures 1.0.0 is out 🎉

Thanks all for your patience and help!

**Comment by siskaj** [comment]
Congratultions an thank you!

I really like them and do use them. 

Jaromir

**Comment by zenkimoto** [comment]
Congrats!  This is a great library and I love using it.

**Comment by tonyarnold** [comment]
Great work, @Thomvis!

**Comment by pellekrogholt** [comment]
Yes very nice work!
