### ISSUE TITLE
Use Result.NoError instead?

### ISSUE THREAD

**Issue by danishin** [Thomvis/BrightFutures#121]
I'm using both `ReactiveCocoa` and `BrightFutures` extensively in my program, and many times I use my custom extension methods to convert back and forth from `ReactiveCocoa.SignalProducer` and `BrightFutures.Future`.

Mostly, conversion is seamless since both frameworks rely on `Result` for propagating errors except when both SP and Future has `NoError` as `ErrorType`. (although I know this can be solved quite easily via `promoteError` method).

ReactiveCocoa recently abandoned its internal `NoError` struct to opt for `Result.NoError` for interoperabilities with other frameworks that rely on Result. 

I know this is a breaking change, but since `BrightFutures` already rely on Result, could we use `Result.NoError` instead of `BrightFutures.NoError` that we have now?

+ Also for the lack of support for aliasing `import`ed symbols, in certain situations, I simply couldn't import all three of Future, Result and RAC. (even using sth like `import enum Result.NoError` wouldn't work becaues we cannot do sth like `import enum Result.NoError as ResultNoError`)

BTW, I love your library. I've always thought RAC was too much abstraction for simple tasks. I hope swift can have `Future` as STL soon :smile:

**Comment by dileping** [comment]
@danishin I already have create [PR](https://github.com/Thomvis/BrightFutures/pull/120) for this. Hopefully guys will merge it soon. Meanwhile feel free to use branch from my fork: [https://github.com/crossroadlabs/BrightFutures/tree/feature-result-update](https://github.com/crossroadlabs/BrightFutures/tree/feature-result-update)

**Comment by Thomvis** [comment]
Thanks for the kind words and thank you for the detailed explanation. 

Indeed, #120 looks like it should resolve this. This change makes a lot of sense and we should have it. As you mention, this is a breaking change, so it seems like BrightFutures 4 will be coming out a bit sooner than I thought ;)

I'll have a look at the PR and hope to merge & release soon.

**Comment by Thomvis** [comment]
This issue has been resolved in BrightFutures 4. Thanks!

**Comment by ngan** [comment]
Hi @Thomvis, from reading this issue, it looks like the recommended thing to do if we currently use `NoError` is to switch to `Result.NoError`? If so, that means that every project that uses BrightFutures will need to add `Result` into their Cartfile as a dependency. I understand that BrightFutures has `Result` as a dependency but best practice would be to include it if you use it yourself--don't rely on your dependencies to always have the library that you're using.  Is there an alternative to no require `Result` in my project?

**Comment by danishin** [comment]
@ngan Actually there is no need for explicitly adding dependency in your cartfile. Carthage supports transitive dependency resolution and it should find `Result` as dependency automatically in the background!

**Comment by Thomvis** [comment]
Thanks @danishin for chiming in. The only thing you should have to do is add 'import Result' to files where you use NoError. This was already the case when you wanted to do some advanced stuff with Result.

Result has been a dependency of BrightFutures for a while now. We prefer it to writing our own Result type to enable better compatibility with other libraries that use Result.

**Comment by ngan** [comment]
Ok thanks guys. But I'm curious what would happen if BrightFutures 5 decides to use something other than Result? I guess at that point I'd have to change everything anyways.

**Comment by Thomvis** [comment]
We treat Result as part of our public API. Any change to the public API requires a major version bump &a with every major version bump anything could change or break. Although the latter is not a goal of course ;)

**Comment by ngan** [comment]
Gotcha!
