### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dileping** [Thomvis/BrightFutures#122]
Hi @Thomvis,

I've recently been working on this and I have it ready. Still, this is a major breaking change, so I'm not even creating a PR. Will appreciate if you could take a look at it here: [https://github.com/crossroadlabs/BrightFutures/tree/feature-linux](https://github.com/crossroadlabs/BrightFutures/tree/feature-linux)

As I'd told you before, we have recently released [Express](https://github.com/crossroadlabs/Express), which uses Futures heavily and now porting it on Linux (almost there, btw). I will very much like to continue using original BrightFutures, but without some certain changes propagated to original repo we will have to keep a separate project which is completely undesired.

Let me know if you are willing to discuss it, please.

Thanks a lot for all the great job you have done so far!
Daniel

**Comment by Thomvis** [comment]
Hi @dileping,

Thanks so much for your work and sorry for not getting back to you sooner. We definitely need to bring BrightFutures to Linux. To be honest, I'm really busy at work at the moment and won't have the time to pick up something big as Linux compatibility for now. I hope to get back to it in a month or so.

In the meantime, I don't have a better solution for you than to use your own branch. I'm sorry.

Best,
Thomas

**Comment by dileping** [comment]
Hi @Thomvis,

this is pretty much what I assumed. We have to move forward (yeah! [Express](https://github.com/crossroadlabs/Express) is already getting quite some popularity!) so I will either keep my fork or even create another implementation, most probably quite some based on what you have done so far. Many thanks for BrightFutures anyways, they are awesome! We just have to move faster.

Kind Regards,
Daniel

**Comment by Thomvis** [comment]
@dileping I completely understand. Good luck with Express!
