### ISSUE TITLE
Custom callbacks

### ISSUE THREAD

**Issue by ngan** [Thomvis/BrightFutures#123]
This is more of a question than an issue. Here goes...

I have a convention is my app where I make a call (via Alamofire) to the server and it returns one of three types of responses: success (2XX), validation errors (422), or unexpected server/client errors (none of the above). This is all communicated with response status codes as indicated in parenthesis. Right now I'm using onSucess for success, and onFailure for the other 2. The thing the kind of sucks right now is everywhere in my onFailure blocks, I have to check which type of error it is before I can process it. What I generally would like to do is only call onFailure for 422 errors and have maybe a separate callback for the other random errors. This is because typically the other random errors are already handled in a central place (like show a pop up and send the user somewhere else). I just need the original caller to clean up after itself with onComplete and don't excute onSuccess or onFailure.

I sort of understand that this would go against principles of success/failure responses only. Any advice on how to solve this problem (either writing or wrapper on top of BF, or an extension)?

Thanks!

**Comment by Thomvis** [comment]
I think you could easily add specific error callback blocks in an extension on the AsyncType. Something like:

```swift
public extension AsyncType where Value: ResultType, Value.Error: YourCustomErrorType {
    public func onValidationFailure(context: ExecutionContext = DefaultThreadingModel(), callback: Value.Error -> Void) -> Self {
        self.onFailure(context) { result in
            // check if the error is a validation error and then call the callback
        }
        return self
    }

}
```

Hope this helps!

**Comment by ngan** [comment]
Thanks! Works great!

I had to write two methods though since `DefaultThreadingModel()` isn't public.

```
public extension AsyncType where Value: ResultType, Value.Error: RequestError {
    public func onValidationFailure(context: ExecutionContext, callback: ValidationError -> Void) -> Self {
        self.onFailure(context) { error in
            if let error = error as? ValidationError {
                callback(error)
            }
        }
        return self
    }
    
    public func onValidationFailure(callback: ValidationError -> Void) -> Self {
        self.onFailure { error in
            if let error = error as? ValidationError {
                callback(error)
            }
        }
        return self
    }
}
```
