### ISSUE TITLE
BrightFutures and podspecs

### ISSUE THREAD

**Issue by jonasman** [Thomvis/BrightFutures#124]
I have a library that imports BrightFutures. My library marks BrightFutures as a dependency in the podspec.

When im trying to validate the podspec to upload to the trunk it always fails because Result is not found.
To fix this i had to mark Result as a dependency to my own library.

I believe this is a bug in BrightFutures podspec. I don't now how to fix it but just to let you know.
My podspec: https://github.com/jonasman/TeslaSwift/blob/master/TeslaSwift.podspec

**Comment by Thomvis** [comment]
Sorry to hear you're having problems. I'm not sure what could be changed in BrightFutures' podspec to improve the use case you're describing. It should work.

Do you have any additional info you can provide that could help us figure this out? Thanks!

**Comment by jonasman** [comment]
Only info could be the error when trying to validate the podspec.

**Comment by rplankenhorn** [comment]
@jonasman I also am pulling in BrightFutures as a dependency but am not having the same issues you are seeing.  The only difference between your podspec file and mine is that I specify BrightFutures version 3.3.0.  Maybe that would work for you?

**Comment by Thomvis** [comment]
I'm closing this issue now, because of inactivity. If you still have the problem, feel free to comment again.
