### ISSUE TITLE
Map future value into Result

### ISSUE THREAD

**Issue by phatmann** [Thomvis/BrightFutures#126]
I have a  `Future<T, E>` that I need to map to a `Future<U, E>`. However, if the mapping fails, I want to return a Future with a failure rather than a success. In pseudocode:

````
return theFuture.map { value in 
    if let newValue = transformTheValue(value) {
        return newValue
    } else {
        // Somehow transform the future into a failing future
    }
}
````

Is this possible given the current set of mapping methods, or do we need a new one?

My workaround now has been to create a new promise and then fulfill or fail this promise within the future's callbacks. But this seems inelegant so I am hoping there is a better way.

**Comment by Thomvis** [comment]
This is a fairly common use case and I'd tackle it by making `transformTheValue` return a `Result`. Then you can use the `flatMap` variant that accepts an `f` that returns a `Result` ([docs](http://cocoadocs.org/docsets/BrightFutures/3.3.0/Protocols/AsyncType.html#/s:FeRq_13BrightFutures9AsyncTypeqq_S0_5Value6Result10ResultType_S_S0_7flatMapu__Rq_S0_qq_S0_5ValueS2__Fq_FFqqq_S0_5ValueS2_5ValueGOS1_6Resultqd__qqq_S0_5ValueS2_5Error_GCS_6Futureqd__qqq_S0_5ValueS2_5Error_)).

Would that work for you?

**Comment by phatmann** [comment]
I failed to notice that there was a version of `flatMap` that took a closure that returned a Result. This is exactly what I needed, so we can close this issue.

By the way, I needed this functionality to write a `first` method on a Future of elements. Here is the code I came up with:

```swift
public protocol ElementErrorType {
    static func noSuchElementError() -> Self
}

extension BrightFuturesError {
    static func noSuchElementError() -> BrightFuturesError {
        return .NoSuchElement
    }
}

public extension Future where T: CollectionType, E: ElementErrorType {
    public var first: Future<T.Generator.Element, E> {
        return flatMap { (array: T)  -> Result<T.Generator.Element, E> in
            if let element = array.first {
                return Result<T.Generator.Element, E>(value: element)
            } else {
                return Result<T.Generator.Element, E>(error: E.noSuchElementError())
            }
        }
    }
}
```

If you think this (and other collection-related methods) would be a useful addition to BrightFutures, let me know.
