### ISSUE TITLE
flatMap compilation error

### ISSUE THREAD

**Issue by jc-paris** [Thomvis/BrightFutures#128]
Hi Thomas,

I run into a strange issue with `.flatMap` that I don't succeed to solve.
I wrote some sample code to reproduce the error:

This compile:
```swift
let future = Future<Int, Error>()
future.flatMap { i in
    return Future<String, Error>()
}
````

This strangely doesn't compile:
```swift
let future = Future<Int, Error>()
future.flatMap { i in
    let f = Future<String, Error>()
    return f
}
```

Neither does this one:
```swift
let future = Future<Int, Error>()
future.flatMap { i in
    let promise = Promise<String, Error>()
    return promise.future
}
```

Any explication ? Is it a BrightFutures issue or me doesn't using it right ?

**Comment by Thomvis** [comment]
Swift is not able to infer the type of multi-line closures. You'll need to something like this:

```swift
let future = Future<Int, Error>()
future.flatMap { i -> Future<String, Error> in
    let f = Future<String, Error>()
    return f
}
```

**Comment by jc-paris** [comment]
Oh right ! Compilation error got me wrong. It's a tricky one !
