### ISSUE TITLE
Support of SPM

### ISSUE THREAD

**Issue by mackoj** [Thomvis/BrightFutures#129]
Hi,

Do you plan to support the swift package manager ?

**Comment by Thomvis** [comment]
Yes, I'd love to, but I won't have the time to do it myself for a while. If somebody (you?) want to work on a PR I'd certainly welcome that!

**Comment by mackoj** [comment]
Ok, I will try do it.

**Comment by Thomvis** [comment]
I've started doing some work for this on https://github.com/Thomvis/BrightFutures/tree/swift-3.0. It was a bit of a painful process and it's not yet done. We need a new Result release as well.

**Comment by TheArtOfEngineering** [comment]
I just submitted https://github.com/mxcl/PromiseKit/pull/425 for PromiseKit. I could certainly do the same for BrightFutures, especially if you are trying to support Swift 3 early. I'd like to use some sort of promise/futures library for https://github.com/TheArtOfEngineering/Edge.

**Comment by Thomvis** [comment]
Hi @TheArtOfEngineering. Thanks for showing interest in the project. I already have a Package.swift on the [swift-3.0](https://github.com/Thomvis/BrightFutures/tree/swift-3.0) branch and `swift build` runs successfully. Can you use that as a starting point and suggest changes if needed? Thanks!

**Comment by wvteijlingen** [comment]
Hi Thomas! What is the status on this? I cannot find a `Package.swift` in master, nor in the swift3.0 branch.

**Comment by Thomvis** [comment]
@wvteijlingen I restarted the Swift 3 migration after my previous comment on this issue and did not include a Package.swift in that effort. The fastest way to get this in would be to submit a PR. Let me know if you're interested in that / need help. Thanks!

**Comment by wvteijlingen** [comment]
Unless BrightFutures has some special build process that I'm not aware of, I think it's just as easy as renaming the "BrightFutures" dir to "Sources" and creating a `Package.swift` containing:

```swift
import PackageDescription

let package = Package(
    name: "BrightFutures",
    dependencies: [
        .Package(url: "https://github.com/antitypical/Result.git", majorVersion: 3),
    ]
)
```

I'll see if I can get around to creating a PR for this tomorrow.
