### ISSUE TITLE
Blocker for release 4.0.0

### ISSUE THREAD

**Issue by davideme** [Thomvis/BrightFutures#135]
I'm using 4.0.0-beta.1 version without any issues, but I cant submit a version of my app to testflight without stripping the version number.

using https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150372394

What are the actual blocker in order to release 4.0.0 ?

**Comment by Thomvis** [comment]
Hi! I don't think there's anything blocking the release per se, but I haven't had much time to use the beta, so I was hoping to get some positive feedback from the community before making it final.

Is the beta working 💯 for you?

**Comment by davideme** [comment]
Yes is working fine. I'm using it, with some mapping of array and sequence, and work as good as previous version, but now on XCode 7.3.
:+1: 
From me and part of all the @karumi team, Thanks!

**Comment by Thomvis** [comment]
BrightFutures 4 is now available. Sorry for the wait!

**Comment by davideme** [comment]
\o/

On Thu, Apr 28, 2016 at 5:19 PM, Thomas Visser <notifications@github.com>
wrote:

> BrightFutures 4 is now available. Sorry for the wait!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Thomvis/BrightFutures/issues/135#issuecomment-215462436>
>



-- 
Davide Mendolia
