### ISSUE TITLE
Support for onComplete on sequence

### ISSUE THREAD

**Issue by davideme** [Thomvis/BrightFutures#136]
I would like on operator on SequenceType that return me form a [Future<>] a [Future<>] where all the future are completed.

Is this possible ?

**Comment by Thomvis** [comment]
I think `sequence()` is what you're looking for: https://github.com/Thomvis/BrightFutures/blob/master/BrightFutures/SequenceType+BrightFutures.swift#L77.

**Comment by davideme** [comment]
No, I'm using sequence in my project, but the problem is that if one of the futures fail, I can't get the data.
My goal is to filter out the kind of error, that correspond to "NotFound" in my context, or to use the filter operator o a array of future.

**Comment by Thomvis** [comment]
You could first call `recover` on each future before putting it in the array and passing it to `sequence`.
