### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by christopher-prince** [Thomvis/BrightFutures#142]
I'm being slovenly and lazy, I know, but there are some questions and comments embedded in the code in these examples:
https://github.com/christopher-prince/TestFutures
Thanks,
Chris.

**Comment by Thomvis** [comment]
Thanks for your feedback! I looked through your project and saw questions, comments and documentation of your own process of understanding. Unsure of which of them you'd like me to address, could you please compose a list here where each item quotes the question/comment with a link to the line in the project for context? That would really help. Thanks again!
