### ISSUE TITLE
How to Log All Failed Promises?

### ISSUE THREAD

**Issue by golfguy0082** [Thomvis/BrightFutures#147]
Hello, I'm trying to figure out the best approach for automatically logging all failed promises.  When using methods that return a future, it is very easy to forget (or be lazy) and not handle error conditions.  I'd like to provide some default logging to help diagnose issues that fall into this bucket.  Do you have any suggestions of a way to inject a hook that would handle this logging?

**Comment by darrenclark** [comment]
It's not automatic unfortunately, but I have used something along the lines of this:

```swift
func logErrors<T, E>(f: Future<T, E>, file: String = #file, line: UInt = #line) -> Future<T, E> {
    return f.onFailure { error in
        print("Future failed: \(error), in '\(file)', line: \(line)")
    }
}
```

Usage:

```swift
func someFunctionReturningAFuture() -> Future<Int, NSError> { ... }

logErrors(someFunctionReturningAFuture())
    .onSuccess { value in
        print("Received value: \(value)")
    }
```

It'll print the error & provide the file & line number where `logErrors` was called.

**Comment by Thomvis** [comment]
Thanks for the PR, I've merged it in! Will make a release soon. Sorry for the delay.

I've added you as a collaborator, so next time you can merge it yourself. If you want. For bigger changes, please use PR's as a way to gather feedback first. Thanks again!

**Comment by Thomvis** [comment]
There's no built in way to do this, but @darrenclark's solution should work. Other solutions might be creating a wrapper type (that also conforms to `AsyncType`) or create a function in an extension of `AsyncType` called `logOnFailure()` or something.
