### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by phatmann** [Thomvis/BrightFutures#150]
Xcode 8 is out! Time to merge the swift-3 branch, please.

**Comment by markst** [comment]
Looks like Result 3.0.0 is out?
https://github.com/antitypical/Result/releases/tag/3.0.0

**Comment by lluisgerard** [comment]
as @markst said, `Result 3.0.0` is out, so the dependency on the `.podspec` should be updated accordingly like in the PR https://github.com/Thomvis/BrightFutures/pull/151

**Comment by Thomvis** [comment]
Swift 3 support has landed in master. I didn't have the time to update the migration guide (https://github.com/Thomvis/BrightFutures/blob/master/Documentation/Migration_5.0.md) so help there would be much appreciated!
