### ISSUE TITLE
Will FutureProofing be getting an update soon?

### ISSUE THREAD

**Issue by kenlaws** [Thomvis/BrightFutures#152]

**Comment by phimage** [comment]
@thomvis if you have no time for `FutureProofing` add me as collaborator
I can update it to swift 3 (after merging my PR https://github.com/Thomvis/FutureProofing/pull/6 of course)

**Comment by Thomvis** [comment]
Thanks for the offer @phimage. I've added you as a contributor to FutureProofing. Looking forward to Swift 3 support!

**Comment by phimage** [comment]
FutureProofing updated to swift 3 https://github.com/Thomvis/FutureProofing/commit/94d42367ab25938a13fe994cf9d6d0cf6ff16ab4

I create a file [BrightFuture+FutureProofing.swift](https://github.com/Thomvis/FutureProofing/blob/master/FutureProofing/BrightFuture%2BFutureProofing.swift) to be able to use generic `Error` into completion handler (It's inspired from PR #108)
Then I add `@escaping` to `materialize` function
Later some code could be reported to BrightFuture
