### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by alickbass** [Thomvis/BrightFutures#153]
I really like using `BrightFutures`. But there is one issue that I face quite often. If you have a sequence of futures it is almost impossible to debug the exact future that fails in a sequence. Maybe it is worth considering some method of debugging like the one that exists in [RxSwift](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#debugging).

**Comment by Thomvis** [comment]
Thanks for your kind words. I really like the debug operator in RxSwift so I definitely think it would make sense to have something like that in BrightFutures. It should be fairly easy to add on top of andThen. Would you be willing to try it and submit a PR?

**Comment by alickbass** [comment]
Sure) I would love to) 👍

**Comment by alickbass** [comment]
Here is the [pull request](https://github.com/Thomvis/BrightFutures/pull/154)

**Comment by alickbass** [comment]
I guess, as PR is merged, we can close this issue
