### ISSUE TITLE
Carthage update fails

### ISSUE THREAD

**Issue by lehovsepyan** [Thomvis/BrightFutures#156]
I have couple of carthage frameworks in my project. It was working fine till today. I just tried to update my carthage frameworks with command: `carthage update --platform ios`
all frameworks besides BrightFutures had been compiled and built fine.

`*** Building scheme "BrightFutures-iOS" in BrightFutures.xcworkspace`
After this step I get a big log with warnings and this message ` 

> ** BUILD FAILED **
> 
> The following build commands failed:
> 	CompileSwift normal arm64
> 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> (2 failures)

My XCode Version is 7.3.1
 
Any ideas how can I solve this ?

**Comment by lehovsepyan** [comment]
I just noticed that you upgraded your code to swift 3 on master branch.
But I still use xcode 7.3.1 with swift 2.2.
Is there a way to use carthage with old versions of your framework ?

**Comment by Thomvis** [comment]
You can point to BrightFutures 4 in your Cartfile, which supports Swift 2.
