### ISSUE TITLE
Why not to use the "monadic" approach

### ISSUE THREAD

**Issue by hfehrmann** [Thomvis/BrightFutures#167]
I think the whole point of the futures is the capability of composing the previous result with the next one and if some computation in the middle of the chain fails, the whole chain fails. This is the monadic approach and allow much more composability. With the current interface of futures `Future<T,Error>` this cannot be achieved, because `Error` cannot be modified by the map method on the result (I actually think this cannot be achieved without hacks).

In Scala, this can be achieved through the for comprehension syntactic sugar. Only at the end of the chain you use `onSucces/onComplete.`

I know that this is a huge amount of work, but i think it must be pointed out.

**Comment by Thomvis** [comment]
BrightFutures uses typesafe error handling, which has some advantages including exhaustive error handling. The downside however is that it is not directly compatible with Swift's error handling. But I do not concur with your conclusion that this prevents BF from being 'monadic'. The Future type has `map` for transforming values and `mapError` for transforming errors. Future inherits these operations from the `Result` type (Future is basically an async wrapper around `Result`).

Knowing this, and using Results' [`materialize`](https://github.com/antitypical/Result/blob/f6e49d4a32492c3861030dfd0d8cf1c4cac044f9/Result/Result.swift#L118) and BF's [`flatMap`](https://github.com/Thomvis/BrightFutures/blob/master/Sources/BrightFutures/AsyncType%2BResultType.swift#L73) you can compose Futures the way you want. An example:

```swift
enum MyError {
    case .httpError(HTTPResponse, NSError)
    case .fluxCapacitorFailure
}

func synchronouslyCalculateFluxCapacitor() throws -> Int {
    // ...
}

func fetch(_ url: String) -> Future<Data, MyError> {
    // ...
}

fetch("http://www.example.org").flatMap {
    materialize(synchronousFailiableOperation()).mapError { .fluxCapacitorFailure }
}
```

It involves an explicit error type transformation, but enables typesafe error handling. In this case, I would have `synchronouslyCalculateFluxCapacitor` probably return a `Result<Int, MyError>`, but even using Swift's error handling it works pretty well.

Hope this helps!
