### ISSUE TITLE
 Library not loaded when using with console applications

### ISSUE THREAD

**Issue by albeva-sainsburys** [Thomvis/BrightFutures#168]
I created a clean swift console project, added `BrightFutures` via Cocoapods and tried to run. Test app compiles fine, but fails to load the framework.

I am using Xcode 8.3.3

Podfile:
```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.12'

target 'GOLServiceManager' do
  use_frameworks!
  pod 'BrightFutures'
end
```

Output in the terminal
```
dyld: Library not loaded: @rpath/BrightFutures.framework/Versions/A/BrightFutures
  Referenced from: /Users/xxx/Library/Developer/Xcode/DerivedData/GOLServiceManager-fiwphglflssziyaqvnfooemqvejc/Build/Products/Debug/GOLServiceManager
  Reason: image not found
(lldb) 
```

Library works fine if the target is iOS app.

**Comment by albeva-sainsburys** [comment]
I should mention that this works fine if I create iOS application and the problem is only with console targets.

**Comment by phimage** [comment]
I think this not not a BrightFutures issue and can be closed

a framework in console application must be available in framework search path. many way to do it
