### ISSUE TITLE
Make map closure throwable?

### ISSUE THREAD

**Issue by aryaxt** [Thomvis/BrightFutures#172]
I think it would be great to make `map` throwable, and in case of throwing trigger onFailure. The usage could be

```
protocol Deserializable {
   init(json: [AnyHashable: Any]) throws
}

func fetch<T: Deserializable>(type: T.Type,  path: String) -> Future<T, NEtworkError> {
   return restClient.fetch(path: path).map {
       return try type(json: $0)
   }
}
```

**Comment by yonaskolb** [comment]
I think `rethrows` would be better so every usage site wouldn't have to add `try` if they don't have a throwing map closure

**Comment by arnopoulos** [comment]
I like the addition of rethrows that way it won't be a breaking API change either

**Comment by aryaxt** [comment]
I think my problem might have been something else, looking at the source it looks like it already throws
