### ISSUE TITLE
Disabled code coverage for xCode 9

### ISSUE THREAD

**Issue by yshindo000** [Thomvis/BrightFutures#175]
If Enable Code Coverage = YES,  iTunesConnect Reject the App.
plz change xcode option.
For more information please see:
Carthage/Carthage#2056

**Comment by yshindo000** [comment]
check this PR
https://github.com/Thomvis/BrightFutures/pull/177

**Comment by Thomvis** [comment]
The PR was merged. Thanks for your work!
