### ISSUE TITLE
Swift 4 Non-Beta Release

### ISSUE THREAD

**Issue by yzhong52** [Thomvis/BrightFutures#178]
Hello!

I notice that there is a beta version that supports swift 4 already, just wondering if there any blocker from pushing that to production? Or there is a timeline for a final release that supports Swift 4?

**Comment by Thomvis** [comment]
Thanks for your question. The final release should have been out already, it's just that I've been travelling for a while. The beta should be fine, there's nothing really beta about it other than that I used an Xcode beta to test it. I'll make a final Swift 4 release soon.

**Comment by yzhong52** [comment]
Okay, @Thomvis, that's awesome! Thanks for confirming this!
