### ISSUE TITLE
Failed when compiling Bitcode

### ISSUE THREAD

**Issue by amjad-Alhusseini** [Thomvis/BrightFutures#181]
I'm trying to export my app which uses Bright Futures under Development distribution method and have checked 'Rebuild from bitcode" and 'Strip Swift symbols.

While it compiles the bitcode i get the following error message:

ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool exited with pid 46226 exit 1
Stdout:
    Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
    Debug: PATH: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode.app/Contents/Developer/usr/bin']
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
    MachoInfo: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" "/var/folders/tr/8nsl_wf97wb29q7x2gmxtcjh0000gn/T/ipatool20171208-38516-yecahh/thinned/armv7/Payload/Aramex.app/Frameworks/BrightFutures.framework/BrightFutures" 

![screen shot 2017-12-10 at 10 08 46 am](https://user-images.githubusercontent.com/10188719/33803189-3e13ef4c-dd92-11e7-97a5-8f5c4c1d2941.png)

I use:
Xcode 9.2
Swift 4 
Carthage 0.26.2
Bright Futures 6.0.0

Am i missing anything or is it not compatible with latest versions?

**Comment by sandeee1928** [comment]
I am facing similar issues. Any suggestion will be appreciated.

**Comment by maharjanbishal** [comment]
how did you fix this?
