### ISSUE TITLE
Compile error on Xcode 9.3 beta 3

### ISSUE THREAD

**Issue by sharplet** [Thomvis/BrightFutures#183]
I raised a Swift bug to track this: https://bugs.swift.org/browse/SR-7059. Hopefully it's caught as a regression and fixed before the GM.

**Comment by Thomvis** [comment]
Thanks for filing an issue! Let’s indeed hope they can fix this before the release.

**Comment by danj-stripe** [comment]
Looks like it won't be included in 4.1, and BrightFutures needs a change:

> Happy to help! Sorry but you'll have to use workaround for now since this was too late in the cycle to make it to 4.1
