### ISSUE TITLE
Swift 4.1 Crashes

### ISSUE THREAD

**Issue by iceman201** [Thomvis/BrightFutures#187]
Swift 4.1 crashes

![image](https://user-images.githubusercontent.com/5027957/38117870-fb6a905a-3413-11e8-89d1-f92ad8e874fd.png)

Generic parameter 'T' could not be inferred

**Comment by guiruiz** [comment]
I'm having the same trouble

**Comment by guiruiz** [comment]
It is fixed on #185

**Comment by iceman201** [comment]
@guiruiz is that available on cocoapod ?

**Comment by Thomvis** [comment]
@iceman201 it is now. Feel free to reopen the issue if you still encounter these problems.
