### ISSUE TITLE
Compile error with XCode 9.3 / Swift 3.3 

### ISSUE THREAD

**Issue by coast111** [Thomvis/BrightFutures#189]
I get the following compile error after upgrading to XCode 9.3. My project uses Swift 3.3.  BrightFutures version is 5.1

..../......Pods/BrightFutures/Sources/BrightFutures/Result+BrightFutures.swift:48:16: Generic parameter 'T' could not be inferred

What are my options to resolve this?

**Comment by markoftheweb** [comment]
In a quick glance it would seem the syntax/code format used in the AsyncType+ResultType.swift file may be the fix. See https://github.com/Thomvis/BrightFutures/blob/master/Sources/BrightFutures/AsyncType%2BResultType.swift#L199 for example of typed return value. 
My short term fix was to comment out that code and confirm that my implementation did not rely on it .. it did not.

**Comment by markoftheweb** [comment]
I think this fixed it ... 
https://github.com/Thomvis/BrightFutures/commit/ae62663680879eb141357f1dc95422814110586e
I copied over to my project and compile error is gone 👍 

By default the version introduced by the `pod install` step was prior to that commit.
