### ISSUE TITLE
Carthage issue with Result version choosing

### ISSUE THREAD

**Issue by ktvtrifork** [Thomvis/BrightFutures#195]
So in various projects I have experienced a rather odd but very specific issue, regarding the combined use of carthage ,brightfutures and result. 
carthage simply chooses a wrong , and VERY old version of result, (in my case 0.6-beta.1), for no obvious reasons.
One solution is to specify the version of result, brighfutures are using, instead of relying on carthage to figure that out. (eventually just pointing to the master branch).
I can create a PR for this if required. 

the only workaround so far found, is to "play" with the cartfile and out-comment the 2 dependencies in various order, until carthage gets confused enough and does not change the versions. 

EDIT:
- commenting out result in cartfile gives  Checking out Result at "3.2.4"
- keeping both gives the 0.6-beta.1 version
- commenting out brightfutues gives the specified version in the cartfile

**Comment by phimage** [comment]
Could we close?
Not reproductible and not enough information

Bug description do not contain Carthage version, if Carthage cache has been removed, if there is other frameworks which use Result, command used with Carthage (there is many...), cartfile, cartfile.resolved, the output log, etc...

To test and debug that you need to download Carthage source and launch with Xcode on your project, make some breaking point where the version is chosen

**Comment by ktvtrifork** [comment]
for future reference linking to https://github.com/Carthage/Carthage/issues/2554 and closing since its a Carthage thing.
