### ISSUE TITLE
Synchronous resolution of Futures

### ISSUE THREAD

**Issue by truizlop** [Thomvis/BrightFutures#200]
I have noticed issue #19, which is similar to the problem that I am having. I need a synchronous way of resolving a Future. I am aware of `forced`, but as stated in the other issue, there is a deadlock in the way that I am using it.

I am using [SwiftCheck](https://github.com/typelift/SwiftCheck) for my tests and I need this synchronous way of resolving a Future in order to be able to compare two different instances. Is there any possibility to overcome this problem?

**Comment by Thomvis** [comment]
Can you give an example of what you’re trying to do, e.g. using `forced` so I can provide relevant feedback. Thanks!

**Comment by truizlop** [comment]
Nevermind, I just found a workaround for what I was trying to do.
