### ISSUE TITLE
Bring consistency between `error` and `failure`.

### ISSUE THREAD

**Issue by wvteijlingen** [Thomvis/BrightFutures#21]
The completion callbacks and Result use `failure`, while Promise uses the word `error`. Is there any reason for this? It seems to me it would be more clear that one leads to another if they were both called either `error` or `failure`.

**Comment by Thomvis** [comment]
I agree. A future/promise either succeeds with a value or fails with an error. I'll rename the methods accordingly.

**Comment by Thomvis** [comment]
I think this is much better: 881346055e411d149fdd98f5a8908f559e25bab4. Agreed?

**Comment by wvteijlingen** [comment]
:+1:
