### ISSUE TITLE
"when" promise?

### ISSUE THREAD

**Issue by arbesfeld** [Thomvis/BrightFutures#28]
Is there a way to run a set of promises simultaneously with this library?

**Comment by durre** [comment]
I think FutureUtils.sequence might be what you're looking for. I think they run in parallell. 

```swift
FutureUtils.sequence([firstFuture, secondFuture]).map { results in
    let firstResult = results[0]
    let secondResult = results[1]

    MyResult(firstResult, secondResult)
}
```

**Comment by Thomvis** [comment]
Short answer: the solution by @durre is probably what you want.

Longer answer:
Promises are not executed, they wrap the result of a task. These tasks (i.e. closures) can be executed simultaneously, depending on the execution context that you pick. By default, the tasks will run on the global queue, thus asynchronously and simultaneously.

If you want to wait for multiple tasks to complete you can indeed use `FutureUtils.sequence`. There are a few examples in the tests:
- https://github.com/Thomvis/BrightFutures/blob/50895c5e2293261f81167bb114ace3844564997b/BrightFuturesTests/BrightFuturesTests.swift#L695
- https://github.com/Thomvis/BrightFutures/blob/50895c5e2293261f81167bb114ace3844564997b/BrightFuturesTests/BrightFuturesTests.swift#L675 (if you only need the first succeeded future)
- https://github.com/Thomvis/BrightFutures/blob/50895c5e2293261f81167bb114ace3844564997b/BrightFuturesTests/BrightFuturesTests.swift#L723 (if you want to filter the results of the set of futures)

**Comment by arbesfeld** [comment]
Thanks!
