### ISSUE TITLE
Promises Chaining

### ISSUE THREAD

**Issue by zenkimoto** [Thomvis/BrightFutures#29]
Hello @Thomvis!  Great project!  I love the simplicity and how the code works.  However, I didn't notice anything in the documentation that would allow for promises chaining like they have in PromiseKit.    I also looked at the code as well.  The andThen() function only supports side effects and not the same idea as chaining promises and I didn't see anything else in the code that would support that functionality.

Is there something I missed or is promises chaining not part of the design of BrightFutures?  Or maybe it's something that's part of the roadmap?  Thanks.

**Comment by Thomvis** [comment]
Hi! Thanks for checkout out BrightFutures.

I think what you're looking for is `map` and `flatMap`. There's an example at the start of the readme:

```swift
User.logIn(username,password).flatMap { user in
  Posts.fetchPosts(user)
}.onSuccess { posts in
  // do something with the user's posts
}.onFailure { error in
  // either logging in or fetching posts failed
}
```

Here we're chaining the result of the `logIn` function to `Post.fetchUser`. You can find more examples in the tests as well. Is this what you're looking for?

**Comment by zenkimoto** [comment]
Hi @Thomvis 

Thanks!  That's exactly what I was looking for!  I guess it never occurred to use a flatMap for promise chaining.  I like this way better as it gives more power by using functional composition.  Great stuff.  Thanks for your help.
