### ISSUE TITLE
Update Cocoapods

### ISSUE THREAD

**Issue by zenkimoto** [Thomvis/BrightFutures#33]
Hello @Thomvis 

Just wanted to let you know that the Cocoapods main repo still has 1.0 beta 2 as the latest version.  In case if other users of the pod don't know there's a new updated version.

http://www.cocoapods.org/?q=brightfutures

**Comment by Thomvis** [comment]
Hi @zenkimoto. Thanks for reminding me! I pushed beta 3 to CocoaPods (see https://github.com/CocoaPods/Specs/commit/5cea1e8d163b25303d6512cd4816f4e77d92e687) and it should become available any minute now.
