### ISSUE TITLE
Support Semantic Versioning?

### ISSUE THREAD

**Issue by zenkimoto** [Thomvis/BrightFutures#43]
Hi @Thomvis 

I was wondering if you would consider supporting semantic versioning in the future for better Carthage support?
https://github.com/Carthage/Carthage#tag-stable-releases
While I use the carthage to check out the master branch, it would be nice to indicate a tag.  (Specific version)  Perhaps consider this after 1.0.0 release (?) as I wouldn't want you to change the current tag scheme that you have now.

**Comment by Thomvis** [comment]
Yes! I use Carthage myself too so I will make sure it will work great. The whole '-beta.7' naming was an unfortunate decision on my part and will be corrected as soon as 1.0.0 goes live (which should be soon!).

**Comment by zenkimoto** [comment]
@Thomvis Sounds Great!!!
