### ISSUE TITLE
Use of unresolved identifier 'FutureUtils'

### ISSUE THREAD

**Issue by divey** [Thomvis/BrightFutures#44]
```swift
var allFutures = [future1, future2]
FutureUtils.sequence(allFutures).onSuccess { result in
    println("complete")
}
```
When attempting to use FutureUtils class like above, I get the following error: 
> Use of unresolved identifier 'FutureUtils'

Looks like the FutureUtils functions were turned into free functions here: 17d4f212d7f1cd80e40042f4197345f4e980f631. But when I change my code to a "free function":

```swift
var allFutures = [future1, future2]
sequence(allFutures).onSuccess { result in
    println("complete")
}
```

I get this error:

> Cannot invoke 'onSuccess' with an argument list of type '((_) -> _)'

Any ideas of how to use the FutureUtils functions? Also, the documentation needs to be updated regarding the FutureUtils methods.

**Comment by Thomvis** [comment]
You're completely right about the documentation regarding FutureUtils. Sorry about that.

In the tests, we do something similar to what you are trying to do: https://github.com/Thomvis/BrightFutures/blob/master/BrightFuturesTests/BrightFuturesTests.swift#L725. Can you try to figure out what the difference is and maybe see what is preventing your case from working?

**Comment by divey** [comment]
Ah, I found the issue. My futures were returning different types. A simple way to recreate: 

```swift
var future1 = Future.succeeded(1)
var future2 = Future.succeeded("string")        
var allFutures = [future1, future2]
sequence(allFutures).onSuccess { result in
    println("complete")
}
```

**Comment by Thomvis** [comment]
Would it work if you explicitly type allFutures as `[Future<Any>]`?

**Comment by divey** [comment]
Doesn't seem to. The following code generates a `'String' is not identical to 'Any'` error on the third line:
```swift
var future1 = Future.succeeded(1)
var future2 = Future.succeeded("string")
var allFutures = [future1, future2] as [Future<Any>]
sequence(allFutures).onSuccess { result in
    println("complete")
}
```
However, adding the cast to the futures themselves does work: 

```swift
var future1 = Future.succeeded(1) as Future<Any>
var future2 = Future.succeeded("string") as Future<Any>
var allFutures = [future1, future2] 
sequence(allFutures).onSuccess { result in
    println("complete")
}
```

**Comment by Thomvis** [comment]
Thanks for the info. I just updated the README and pushed version 1.0.1. I'm closing this issue.
