### ISSUE TITLE
How to pass a Promise to a method

### ISSUE THREAD

**Issue by ngan** [Thomvis/BrightFutures#46]
I have the following:

```swift
func promiseProvider() -> Future<User> {
  let promise = Promise<User>()

  promiseHandler(promise)

  return promise.future
}

func promiseHandler<T>(aPromise: T) {
  // do something with he promise:
  promise.success(User())
}
```

I'm basically trying to pass the promise I created in `PromiseProvider` to another method (`promiseHandler`).  But for whatever reason, Swift complains:
`Cannot invoke 'promiseHandler' with an argument list of type '(Promise<User>)'`

Any help would be appreciated, thanks!

**Comment by Thomvis** [comment]
It looks like you removed some bits from the actual code that might have to do with the error you're seeing.

However, in your example, when you do `promise.success(User())`, you're calling `success` on `T`, and Swift has no way of knowing whether `T` will have that method.

**Comment by ngan** [comment]
I got it to work like this:
```swift
func promiseHandler <T>(promise: Promise<T>) {
  // do something with he promise:
  promise.success(User())
}
```

Thanks!
