### ISSUE TITLE
It's not possible to use v2.0.0-beta.2 via pods

### ISSUE THREAD

**Issue by i-schuetz** [Thomvis/BrightFutures#58]
The v2.0.0-beta.2 tag has wrong version in podspec:  s.version = '2.0.0-beta.1'

So it doesn't seem to be possible to install beta 2 via pods. (Note that using direct git reference in pods doesn't help - this also installs beta 1:
    pod 'BrightFutures', :git => 'https://github.com/Thomvis/BrightFutures.git', :tag => 'v2.0.0-beta.2')

**Comment by Thomvis** [comment]
Thanks for noticing. I fixed it by pushing a new version of the 2.0.0-beta.2 podspec to CocoaPods. I am now able to install it by putting the following in the Podfile:

`pod 'BrightFutures', '2.0.0-beta.2'`
