### ISSUE TITLE
Complete a future multiple times?

### ISSUE THREAD

**Issue by i-schuetz** [Thomvis/BrightFutures#59]
So far I'm seeing this is not possible. I'm looking for a way to replace callback logic where the callback is executed 2 times.

The reason I have this is a webservice call with a local-database cache. I always return to the caller the result of the local database and do webservice call in the background. If the result of the webservice call is different from the result which I returned from the local db, I return this result (again) to the caller. So my callback can be executed 1 or 2 times. The idea is to show the cached result to the client as soon as possible, and if there's a change in the remote data to refresh the UI immediately with it.

Previously I had (roughly) something like:

```swift
func myCall(handler: (MyResult) -> ()) {
    getFromLocalDB {localDBResult in
         handler(localDBResult)
    }

    getFromRemote {remoteResult
         //...
         if remoteResult != localDBResult {
             handler(remoteResult)
         }
    }
```

This is what I came up as replacement using futures (I have little experience with futures, maybe there's a better way):

```swift
func myCall() -> Future<MyResult, NSError> {

    let promise = Promise<MyResult, NSError>()

    getFromLocalDB.onComplete {result in
         // ...
         promise.success(localDBResult)
    }

    getFromRemote.onComplete {result
         // ...
         if remoteResult != localDBResult {
             promise.success(remoteResult)
         }

    return promise.future
}
```

But this causes an assertion error on the second success call because the future is already completed.

I came up with a solution in which I return 2 futures, like this:

```swift
func myCall() -> (cached: Future<MyResult, NSError>, remote:  Future<MyResult, NSError>) {

    let promiseCached = Promise<MyResult, NSError>()
    let promiseRemote = Promise<MyResult, NSError>()

    getFromLocalDB.onComplete {result in
         // ...
         promiseCached.success(localDBResult)
    }

    getFromRemote.onComplete {result
         // ...
         if remoteResult != localDBResult {
             promiseRemote.success(remoteResult)
         }

    return (cached: promiseCached.future, remote: promiseRemote.future)
}
```

And handle with a common closure: 

```swift
let completion: Result<[MyResult], NSError> -> () = {result in
    // ...  
}

let (cached: Future<[MyResult], NSError>, remote: Future<[MyResult], NSError>) = getMyResults()

cached.onComplete { // this additional closure is necessary - somehow it was not possible to pass the completion closure directly 
    completion($0)
}
remote.onComplete {
    completion($0)
}
```

And that works, but I wonder if there's a better way. Having the handler callback called twice is maybe not the cleanest way to implement this, but there may be other scenarios with a callback-similar setup which has to be called multiple times.

**Comment by Thomvis** [comment]
A future is something that completes once and only once. It is a feature, but also a restriction. A restriction you seem to be running into. I think there is a good solution for this problem using futures, but you could also look into using a Signal (e.g. with ReactiveCocoa).

A possible solution to your issue.

Create a type `DataResult`:

```
enum DataResult<E> {
    case CacheMiss(Box<E>)
    case CacheHit(Box<E>, Future<E, NSError>)
}
```

`myCall` will return a future with this type:

```
func myCall() -> Future<DataResult<[ListItem], NSError> { ... }
```

When you call `myCall` you can handle both the cache miss & hit scenario's:

```
myCall().onSuccess { dataResult in
    switch dataResult {
        case .CacheMiss(let boxedValue)
            handleData(boxedValue.value)
        case .CacheHit(let boxedValue, let future):
            handleData(boxedValue.value)
            future.onSuccess(handleData)
    }
}

func handleData(list: [ListItem]) {
    
}
```

Does this help?

**Comment by i-schuetz** [comment]
Not sure how this solves my issue. As I wrote I want to be able to call the handler twice (once when there's a cache hit and the other, after it, when there are results from remote provider, and they are different from cache). Here myCall() returns a single future and onSuccess can be called only once. This is why I came up with the solution where I return a tuple with 2 futures, one with the cache response, and the other with the remote response...

**Comment by Thomvis** [comment]
A future will only complete once, there's no way around that. However, there are ways to work around/with this. Both your own example as well as my suggestion offer a workable solution, in my view.

The advantage to the approach I suggested is the safeness that you get by using the enum. It describes all possible cases exhaustively. You could even abstract away the whole handling of that enum to make it even nicer:

```
func handleDataResult<E>(f: Future<DataResult<E, NSError>>, callback: E -> ()) {
	myCall().onSuccess { dataResult in
	    switch dataResult {
	        case .CacheMiss(let boxedValue)
	            handleData(boxedValue.value)
	        case .CacheHit(let boxedValue, let future):
	            handleData(boxedValue.value)
	            future.onSuccess(handleData)
	    }
	}
}
```

In code, you could then do:

```
handleDataResult(myCall) { val in
	// this closure is called twice
}
```

In Swift 2, you could even go further by defining a `handleDataResult`-like function on futures that complete with `DataResult` using protocol extensions.

**Comment by i-schuetz** [comment]
Sorry, my phrasing was probably misleading, I meant to call my handler twice, not the future's completion handler, it's clear now that this can be executed only once.

Now I think I also get your example. It's a bit confusing, though, because the case names seem to be incorrect. The .CacheMiss case seem to correspond to cache hit and .CacheHit to the case where the result is fetched from the server...

**Comment by Thomvis** [comment]
Ok, thanks for clearing that up. We now agree that calling your handler is both desirable and possible :)

If you have no further questions, feel free to close the issue. Thanks!

**Comment by i-schuetz** [comment]
Thanks for your help!
