### ISSUE TITLE
Is it possible to use 1.0 with Swift 2 until 2.0 is ready?

### ISSUE THREAD

**Issue by aputinski** [Thomvis/BrightFutures#60]
I'm currently updating my app for Swift 2.0, but can't get my app to run with any of the Swift 2.0 branches using Carthage.

I was able to (after some hacking) get the "swiftier-2.0" branch to build with Carthage, but I kept getting a fatal error whenever I would call `onSuccess`

**Comment by aputinski** [comment]
I was finally able to get the `swift-2.0` branch to build correctly.

**Comment by Thomvis** [comment]
@aputinski Good to hear. If there's anything I could change to make it easier, let me know!

**Comment by aputinski** [comment]
@Thomvis Thanks! Not sure what your timeline is for having 2.0 ready, but maybe a quick note in the README about which branch to use if you're using Swift 2.0.

Thanks again for this framework — really love using it.

**Comment by Thomvis** [comment]
@aputinski Yes! This needs to be better. I've been a bit busy lately but hope to release BrightFutures 2.0 (for Swift 1.2) this weekend and also release an 'official' beta for Swift 2.0.
