### ISSUE TITLE
ENABLE_BITCODE

### ISSUE THREAD

**Issue by aputinski** [Thomvis/BrightFutures#63]
Just updated to `v3.0.0-beta.1` and Carthage builds, but emits the following error:

`ld: warning: -weak_framework is treated as -framework when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES). Weak linking may still happen based on availability mark-up in headers`

**Comment by Thomvis** [comment]
If I'm building BrightFutures on its own using `carthage build --no-skip-current --verbose`, I'm not seeing the error. Could this have to do with a setting in your client project?

I found this issue https://github.com/CocoaPods/CocoaPods/issues/3661 which seems related, but you're using Carthage, not CocoaPods.

**Comment by aputinski** [comment]
Sorry about that, just did some testing and it wasn't BrightFutures. Carthage just emits the warnings at the end, so it appeared the warnings were coming fro, BrightFutures.
