### ISSUE TITLE
Safe to naïvely use 'self' methods?

### ISSUE THREAD

**Issue by fwielstra** [Thomvis/BrightFutures#65]
Probably best explained with a code example. I have a UIViewController which fetches data wrapped in BrightFutures, and on completion fills in that data in its views - simple enough:

```swift
class SomeViewController: UIViewController {

    override func viewDidAppear() {
        super.viewDidAppear()
        // loadUser returns a Future
        User.loadUser().onSuccess(callback: displayUser)
    }

    func displayUser(user: User) {
        println("displaying user \(user)")
    }
}
```

What happens if SomeViewController was deallocated before the loadUser future resolves? Does BrightFutures retain the callback method and the relevant object associated with it, or do I need to always wrap it in a 'weak self' wrapper like so:

```swift
    User.loadUser().onSuccess { [weak self] user in
      self?.displayUser(user)
   }
```

I much prefer the first form - and preferably an even simpler one (currently the callback argument name is required). It's already a huge improvement over the existing success/failure block or delegate method approaches used, IMO.

(note: Swift 1.2, BrightFutures 2.x)

**Comment by Thomvis** [comment]
The first approach retains self and I don't think there is anything that BrightFutures can do to prevent that.

(When googling this, I found a blogpost on this topic by a colleague of yours: http://blog.xebia.com/2014/10/09/function-references-in-swift-and-retain-cycles/)

**Comment by fwielstra** [comment]
All right, that's what I was looking for. Coincidentally, that colleague of mine is sitting right next to me, ran through the code, and concluded the same thing :p
