### ISSUE TITLE
Doesn't work with xCode plugin template

### ISSUE THREAD

**Issue by gerchicov-bp** [Thomvis/BrightFutures#74]
Cocoapods doesn't work at all.

Carthage works but I can't add it to my project properly - it simply doesn't have "General tab" for binaries and etc. And so I can't simply include your library.

Could you advice another solution?

**Comment by Thomvis** [comment]
Can you describe what you mean by "Cocoapods doesn't work at all."? I am able to integrate BF into my projects using CocoaPods just fine.

**Comment by gerchicov-bp** [comment]
Sorry, I have created similar issues for other similar projects and forgot to update them all.
ReactiveCocoa, PromiseKit and BrightFutures can't be used in "xcode plugin" project.

Steps to reproduce:
1)install Alcatraz (or use another way to perform step 2)
2)install "xcode plugin template" via Alcatraz
3)create an empty project and try to use BrighFutures in it
I hadn't found a way how to use it in code except of importing it as sources, not framework. But in my case it is even more complex task to detach these sources from the framework than using of standard Objective C methods.

**Comment by Thomvis** [comment]
I have no experience with xcode plugin projects and what (potentially) makes them different from other projects so I'm afraid I won't be able to help. If your issue is resolved at any of the other projects you mention (ReactiveCocoa & PromiseKit), let me know!

**Comment by gerchicov-bp** [comment]
sorry but still nothing. Anyways Could you explain what do you additionally add to the framework which makes it impossible to use BrightFutures as simply source code files?

**Comment by Thomvis** [comment]
I'm sorry that I wasn't able to help in a timely fashion. 

I'm going close this issue for now. If you are still encountering the same issue, please feel free to comment again and I'll reopen. Please provide as much information as possible. Thanks!
