### ISSUE TITLE
Improve future composition

### ISSUE THREAD

**Issue by zhaar** [Thomvis/BrightFutures#76]
Hi, 
I'm having a lot of issues handling the error type when composing futures.

Typically:
```swift
let three: Future<Int, NoError> = future(3)
let fut: Future<Int, NSError> = future { //long computation that can fail }
let composed =fut.flatMap { _ in three)
```
Produces an compile error. But it all works when both futures have the same Error Type.

I expected `composed` to be of type `Future<Int, NSError>` because one of the error type is a Void type, only the other one makes sense.
If both types conform to `ErrorType` then I would expect a generic `ErrorType` on which I can patten match or a composed error (like a tuple of optional errors).

Is there a way of achieving this behaviour? Is it intended? Am I doing something wrong?

**Comment by Thomvis** [comment]
You can use `promoteError` to change the error type of `three` from `NoError` to any other error type (in this case `NSError`).

Let me know if that does the trick for you!

**Comment by zhaar** [comment]
It worked! 
But it feels clunky. Why isn't this the default behaviour when composing futures with NoError?

before your answer I "fixed" my problems by converting my all my futures into Future<T?, NoError> so that they would play nice.

Now, using the promote error function, everything works fine and more elegantly

**Comment by Thomvis** [comment]
I guess variants of `map`, `flatMap`, etc. that know how to handle futures with `NoError` could be added. Not sure if it is worth the extra code. If you think so, you could try making a PR. Thanks!
