### ISSUE TITLE
function signature specialization?

### ISSUE THREAD

**Issue by thegreatmichael** [Thomvis/BrightFutures#77]
I'm having trouble deciphoering an error, and it's listed in my code (rather than a BrightFutures file) so probably it's my own bug, but in case it's meaningful I wanted to post here (and perhaps you'll have seen something like this before?)

    function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of MyPackage.MyFile.myFunction (MyFile.myFunction)(ObjectiveC.NSMutableDictionary, then : () -> ()) -> () (MyFile.swift:1562)

**Comment by Thomvis** [comment]
Hm, I've never seen this error and I'm not sure what it means. Like you mention, I think it has nothing to do with BrightFutures.

I'll close this issue for now, but feel free to comment when you find out what is going on.
