### ISSUE TITLE
best way to implement retry 

### ISSUE THREAD

**Issue by connectdotz** [Thomvis/BrightFutures#78]
while there are flatMap to chain futures for successful results, what is the best way to do retry kind of logic when there is failure? i.e. how do we chain futures for failure path?

**Comment by Thomvis** [comment]
BrightFutures has no built-in retry mechanism, but you can easily roll your own using `recoverWith`. Here's an example of a function that retries `fetchData` once:

```
func retryingFetchData(retry: Bool = true) -> Future<NSData, Error> {
	let f = fetchData()
	if (retry) {
		return f.recoverWith { err in
			return retryingFetchData(false)
		}
	}

	return f
}
```

**Comment by connectdotz** [comment]
ok, we could work with that...

BTW, this library is pretty awesome, we are finding goodies everyday, thanks for opensource it.
