### ISSUE TITLE
exploring persistent future as notification alternative

### ISSUE THREAD

**Issue by connectdotz** [Thomvis/BrightFutures#79]
Hello,

We would like to have a more functional notification mechanism due to the following problems in current IOS Notification system:
* the signature is loose (userInfo), not able to take advantage of swift's powerful compile type checking
* not possible to declare composition like flatMap
* only classes can post notifications right now

Both notification and futures let user register future events and handlers, so at least conceptually it seems like a natural extension for futures to handle such use case. The main obstacle for the current BrightFutures implementation is the assumption that future is only **executed once**, any subsequent completion/callback attempts are treated as illegal state. If this behavior can be configured or allow subclass to override, we should be able to use this **persistent future** to model the notification use case... 

thoughts, concerns or gotcha?

**Comment by Thomvis** [comment]
If you want a future that executes multiple times, you are running into stream/signal territory. I think it would be hard to add this behavior as an optional configuration and trying to do so would harm the simplicity of BrightFutures.

I'd probably look into using [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) or [RxSwift](https://github.com/ReactiveX/RxSwift).
