### ISSUE TITLE
New workaround needed for the "non-fixed multi-payload" bug

### ISSUE THREAD

**Issue by bkase** [Thomvis/BrightFutures#8]
In Xcode Beta 6, compiling BrightFutures gives the following error:

`'__conversion' functions are no longer allowed`

It looks like there is not another way to do an implicit type conversion to workaround the .Success value in the TaskResult enum. Unfortunately, writing the code as it should be written:

```swift
public enum TaskResult<T> {
  case Success(T)
  case Failure(NSError)
  ...
}
```

still results in an "unimplemented IR generation feature non-fixed multi-payload enum" error.

I think it is necessary to expose the unboxing of the generic value to users of the API, but I didn't want to make a pull-request in case you had a good solution.

**Comment by Thomvis** [comment]
Like everybody, we're still boxing the success value in Result and it's fine for now. Closing this issue.
