### ISSUE TITLE
Dependency 'Result', '0.6-beta.1' causing newer frameworks to break

### ISSUE THREAD

**Issue by zbeckman** [Thomvis/BrightFutures#80]
Your podspec includes:
```
  s.dependency 'Result', '0.6-beta.1'
```
Unfortunately this is causing newer frameworks (such as ReactiveCocoa, Swift 2 branch), Moya, and others to break:
```
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /Users/zbeckman/Library/Developer/CoreSimulator/Devices/FCFAAFBF-1AB4-4223-9BCC-CA91CBDE96DC/data/Containers/Bundle/Application/9E7272D7-5C66-48F9-9E37-892E41662655/Glimpulse.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: Incompatible library version: ReactiveCocoa requires version 1.0.0 or later, but Result provides version 0.6.0
(lldb) 
```

**Comment by Thomvis** [comment]
I'm sorry you're experiencing problems!

The error message states that ReactiveCocoa requires Result version 1.0.0, but that version does not exist. 0.6-beta.1 is the newest. Also, I've read the ReactiveCocoa issue, but I'm unfortunately not following why the conclusion there is that BrightFutures is the problem.

Can you explain what you think I should change to make it work? I hope I can help!

**Comment by orta** [comment]
You have to manually define what version of Result you use in your Podfile until there's an official tag + release.

**Comment by Thomvis** [comment]
Thanks @orta for chiming in. If I understand you correctly, there's not much I can do from the BrightFutures side and @zbeckman should update the Podfile to point to a specific version of Result.

Let me know if that works @zbeckman!

**Comment by zbeckman** [comment]
I'm afraid I have no control of ReactiveCocoa...

**Comment by Thomvis** [comment]
If you're still having problems, it would help if you'd post your Podfile here.

**Comment by Thomvis** [comment]
I've updated/fixed the BrightFutures podspec, which does solve some problems with the Result dependency. I'm going to close the issue for now, but feel free to reply if you have new information.
