### ISSUE TITLE
Compile error: `direct generic type metadata pattern for Result.Result`

### ISSUE THREAD

**Issue by nRewik** [Thomvis/BrightFutures#81]
I use BrightFutures with Alamofire

I write extension for Alamofire.Request.

`request.responseJSONPromise()` run with no error.

However, when I chain `Future` using `flatMap`, Xcode7 shows a compile error message.

![screen shot 2558-09-19 at 15 54 40](https://cloud.githubusercontent.com/assets/6581089/9975462/38cafe26-5ee7-11e5-8ca9-d3dca62f76a3.png)

Here's my code

```swift
public func getToken(username username: String, password: String) -> Future<String, DRCloudServerError> {

    let request = Alamofire.request( .POST, url, parameters: params)

    return request.responseJSONPromise().flatMap{ json -> Future<String, DRCloudServerError> in
        
        let promise = Promise<String, DRCloudServerError>()
        if let accessToken = json["access_token"].string{
            promise.trySuccess(accessToken)
        }else{
            promise.tryFailure(DRCloudServerError.JSONParseError)
        }
        return promise.future
    }
}
```
and my Alamofire.Request extension
```swift
extension Alamofire.Request{
    
    func responseJSONPromise() -> Future<JSON,DRCloudServerError>{
        
        let promise = Promise<JSON, DRCloudServerError>()
        responseJSON{ request, response, result in
            
            if let error = self.handleStatusCodeError(response, data: result.data){
                promise.tryFailure(error)
            }
            
            switch(result){
            case let .Failure(_, error):
                let errorDescription = "\(error)"
                promise.tryFailure(DRCloudServerError.RequestError(errorDescription))
            case let .Success(value):
                let json = JSON(value)
                promise.trySuccess(json)
            }
        }
        return promise.future
    }
}
```

**Comment by Thomvis** [comment]
Hi and sorry to hear you're having problems using BrightFutures.

Can you try rewriting the implementation of `getToken`, e.g. splitting up parts of the expression and adding more type info? It sounds like a limitation of the compiler to me, which you can try to work around by rewriting expressions and/or adding more type info.

**Comment by nRewik** [comment]
Thank you @Thomvis . I've tried to split up the code and add more type info. Xcode still shows me the same message.

However, I write the same code in the new project with same Podfile, then it works. 

I really have no Idea what's happened.

**Comment by levous** [comment]
I am getting the same compiler error.  
```
Undefined symbols for architecture x86_64:
  "direct generic type metadata pattern for Result.Result", referenced from:
      type metadata accessor for Result.Result<Swift.Bool, After.LovableError> in VibeDetailViewController.o
      type metadata accessor for Result.Result<(loved : Swift.Bool, lovedByCount : Swift.Int), After.LovableError> in VibeDetailViewController.o
```

I have no clue what that means :-/

**Comment by ostap0207** [comment]
Having the same problem. I use BrightFutures + Alamofire. As a workaround added `import Result`, which solved the problem. But would be good to have proper solution.

**Comment by athensholloway** [comment]
I was having the same issue when chaining promises in my view controller. I solved the problem by adding ```import Result``` as well.
