### ISSUE TITLE
Conditional Future chaining

### ISSUE THREAD

**Issue by BrunoBerisso** [Thomvis/BrightFutures#82]
Hi,

Just start using BrightFutures and it's really fun! Thanks for the work done :)

I have a question, recently hit this patter two times:
```swift
future {
    //Do some computation
    return Result(value: successValue)
}.flatMap { goodValue in
    if goodValue.holdSomeCondition() {
        return doSomethingElse()
    } else {
        return Future(value: goodValue)
    }
}
```
The question is, how can I avoid the ```flatMap``` when the condition isn't true? I found ```filter``` but if the condition is false the operation fail. I could do the ```filter``` and handle the error but I don't like it much.

Thanks

**Comment by Thomvis** [comment]
Thanks for your kind words!

I don't think there's a more elegant way to do this, yet. Perhaps if Swift would add a way to incorporate pattern matching in custom places we could make something like what you're looking for.

The alternative to what you have right now would probably be a combination of `filter` and `recover`, but I think the solution you have right now is better.

I hope that helps!
