### ISSUE TITLE
Concurrent queues

### ISSUE THREAD

**Issue by mickeyreiss** [Thomvis/BrightFutures#85]
It looks like `Queue` only exposes a mechanism for creating queues that are `DISPATCH_QUEUE_SERIAL`. 

Is there a reason you decided not to include a way to create a concurrent (`DISPATCH_QUEUE_CONCURRENT`) queue directly?

**Comment by Thomvis** [comment]
There's no real reason other than that I don't need concurrent queues inside BrightFutures.

I've added a way to create a Queue with custom queue attributes. Let me know if this solves the issue.
