### ISSUE TITLE
How to provide a <NOTHING,Error> Future?

### ISSUE THREAD

**Issue by malcommac** [Thomvis/BrightFutures#95]
Hi,
Am I missing something? Can I return nothing (nil, no objects) if promise succeded and error if fails?
Right now I'm returing a Bool but it always true and I've added it just to make the compiler happy :)

**Comment by Thomvis** [comment]
I've run into this issue myself before. What I ended up doing is using `Void` as the success value type. You can see examples of this in the tests, e.g. [here](https://github.com/Thomvis/BrightFutures/blob/master/BrightFuturesTests/BrightFuturesTests.swift#L67).

Hope this helps!

**Comment by malcommac** [comment]
Great, perfect. Thank you!
