### ISSUE TITLE
Drop the ErrorType constraint

### ISSUE THREAD

**Issue by nikita-volkov** [Thomvis/BrightFutures#97]
What is the purpose of this? I see no practical benefit and I see a major downside of it disallowing me to reuse the existing types for errors, e.g. `String`.

[A similar mistake](http://hackage.haskell.org/package/transformers-0.4.3.0/docs/Control-Monad-Trans-Error.html) was made in Haskell some time ago, and it has been criticised extensively ever since, e.g. see the "Why not ErrorT?" section of [this post](http://www.haskellforall.com/2012/07/errors-10-simplified-error-handling.html).

**Comment by Thomvis** [comment]
You make a good point and I think there is no good reason to keep E restricted to ErrorType. The first version of BF only supported NSError and the change to any `E: ErrorType` was big enough for me not to see that E doesn't need to be constrained.

There is however a technical reason why this is not possible at the moment: we rely on [Result](https://github.com/antitypical/Result), which restricts E to ErrorType. I think they also have some doubts about this restriction, so it could change. If you want you could open the issue there or else I could do it myself.

**Comment by Thomvis** [comment]
I brought this up at https://github.com/antitypical/Result/issues/131. Result is not going to change now, so this issue cannot be fixed. Thanks for bringing it up though, let's re-evaluate in the future.
