### ISSUE TITLE
Upgrade to Results 1.0.0

### ISSUE THREAD

**Issue by brassel** [Thomvis/BrightFutures#98]
Hi there and thanks for this great library!

I'd like to ask if it would be possible to upgrade your dependency to Results 1.0.0 instead of the beta version added currently. It does not only give people a bad feeling to submit apps with beta versions, it does also cause real issues in the submission process.

This would be great!
Bernd

**Comment by Thomvis** [comment]
Thanks for filing the issue. It has been merged with PR #99!
